### PR TITLE
Better Linux and Mac Support

### PR DESCRIPTION
**Pull request by mbway**
- removed the need for a separate script when calling xclip
    - based on [this gist](https://gist.github.com/olejorgenb/a5194d9bc183dbe0bfb02aac18fe37f9)
- merged the two lua scripts into one by detecting the platform at runtime

I haven't touched the javascript version. it might make sense to remove this or also upgrade it to support both platforms to avoid confusion?

### CODE REVIEW

**Comment by nwparker** [comment]
Tested on Mac

The copy code works, but the OS determining logic does not. I'm not sure why.

Probably best to test for existence of xclip or pbcopy for determining the OS (or just try both commands in a try catch?)

**Comment by mbway** [comment]
does it work for you now? The script now is pretty much a complete rewrite of the original code (with the maths cleaned up as well) but it doesn't look like it will ever be merged anyway

**Comment by r-bassi** [comment]
Didn't work for me initially, I had to remove the if-statement that checks if the command pbcopy exists. Worked like a charm after that. I'm on MacOS 11.6.1. Thanks for the script, this will save me a lot of time!

**Comment by mbway** [comment]
do you have any details on why `command_exists` might be failing? I assume from your description that that is the problem

**Comment by r-bassi** [comment]
Not sure, I didn't go too deep into debugging the command_exists function since I know for a fact pbcopy will work on MacOS. I'm also not super familiar with lua or how you would go about platform detection without some hacky solution. Maybe consider: https://stackoverflow.com/a/295062

**Comment by nwparker** [comment]
The lazy solution here would be to simply invoke both commands (regardless
of failure)

**Comment by mbway** [comment]
> Maybe consider: https://stackoverflow.com/a/295062

I now think that it's better to detect what programs are available rather than what OS is running as Linux + Wayland will need to use wl-copy but Linux + X11 can use xclip

I used an OSX VM to investigate the issue. The problem came from `echo -n` not working on Mac OS when using `/bin/sh` which is what `os:popen` seems to use. Rather than `-n` omitting the newline it instead prints out literally `"-n 0"`. It does work correctly in regular bash shells though. Apparently the more portable option is `printf`.

`command_exists` should work on mac and Linux now

**Comment by mbway** [comment]
I added wl-copy support for wayland. Tested on Fedora 35 (running Gnome 41 with Wayland).
For some reason xclip also works on wayland but this supports both anyway.

**Comment by Arieleg** [comment]
Thank you for the contribution.

**Pull request merged**
